export const QUIZ_GETTING_QUIZ = 'QUIZ_GETTING_QUIZ';
export const QUIZ_GET_QUIZ_SUCCESS = 'QUIZ_GET_QUIZ_SUCCESS';
export const QUIZ_GET_QUIZ_FAILED = 'QUIZ_GET_QUIZ_FAILED';

export const QUIZ_SAVE_QUESTION_ANSWER = 'QUIZ_SAVE_QUESTION_ANSWER';
